import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#00193b",
        "primary-container": "#032d60",
        "on-primary": "#ffffff",
        "on-primary-container": "#7896cf",
        "primary-fixed": "#d7e2ff",
        "primary-fixed-dim": "#abc7ff",
        "on-primary-fixed": "#001b3f",
        "on-primary-fixed-variant": "#26467a",
        secondary: "#00658e",
        "secondary-container": "#43beff",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#004a6a",
        "secondary-fixed": "#c7e7ff",
        "secondary-fixed-dim": "#84cfff",
        "on-secondary-fixed": "#001e2e",
        "on-secondary-fixed-variant": "#004c6c",
        tertiary: "#101b21",
        "tertiary-container": "#253036",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#8c989f",
        "tertiary-fixed": "#d8e4ec",
        "tertiary-fixed-dim": "#bcc8d0",
        background: "#f9f9ff",
        "on-background": "#001b3f",
        surface: "#f9f9ff",
        "surface-dim": "#cadaff",
        "surface-bright": "#f9f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f1f3ff",
        "surface-container": "#e8eeff",
        "surface-container-high": "#dfe8ff",
        "surface-container-highest": "#d7e3ff",
        "surface-variant": "#d7e3ff",
        "on-surface": "#001b3f",
        "on-surface-variant": "#43474f",
        "inverse-surface": "#13305a",
        "inverse-on-surface": "#ecf0ff",
        "inverse-primary": "#abc7ff",
        outline: "#747780",
        "outline-variant": "#c4c6d1",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["var(--font-plus-jakarta-sans)", "Plus Jakarta Sans", "sans-serif"],
        headline: ["var(--font-hanken-grotesk)", "Hanken Grotesk", "sans-serif"],
        label: ["var(--font-hanken-grotesk)", "Hanken Grotesk", "sans-serif"],
      },
      borderRadius: {
        card: "24px",
        xl: "1.5rem",
        lg: "0.75rem",
        md: "0.5rem",
        sm: "0.25rem",
      },
      spacing: {
        base: "8px",
        gutter: "24px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
        "container-max": "1280px",
      },
      boxShadow: {
        ambient: "0 24px 32px -12px rgba(0, 25, 59, 0.05)",
        "ambient-hover": "0 32px 48px -12px rgba(0, 25, 59, 0.1)",
        glass: "0 8px 32px 0 rgba(0, 25, 59, 0.05)",
      },
    },
  },
  plugins: [],
};

export default config;
